### ISSUE TITLE
[个人建议]为basic和monitor的服务加上hostname，更便于单机部署学习

### ISSUE THREAD

**Issue by tanjianhui1979** [prontera/solar#41]
为basic和monitor的服务加上hostname如：
```
services:
    jce_java:
        build: ./docker-jce-jre
        image: pronter/jce-java
        read_only: true
        command: echo "jce java"
        environment:
            - TZ=Asia/Shanghai
    gateway:
        hostname: gateway
        build: ./api-gateway-ms
        image: prontera/gateway-ms
        ports:
            - "7291:7291"
            - "10211:10211"
        depends_on:
            - 'jce_java'
        environment:
            - TZ=Asia/Shanghai
```

然后在主机hosts文件中为所有服务hostname映射：
127.0.0.1 solar_mysql 
127.0.0.1 rabbitmq 
127.0.0.1 eureka1 
127.0.0.1 eureka2
127.0.0.1 config_server
127.0.0.1 zipkin_server
127.0.0.1 gateway
127.0.0.1 hystrix_dashboard
127.0.0.1 spring_boot_admin
127.0.0.1 zipkin_server
127.0.0.1 account
127.0.0.1 membership
127.0.0.1 product
127.0.0.1 tcc_coordinator
